name: gpu_access_test


services:

  test:
    image: rr5555/gpu_access_test:test_both
    runtime: nvidia
    privileged: true
    deploy:
      restart_policy:
        condition: on-failure

    volumes:
      - ./code:/code
    entrypoint: >
      bash -c "python3 /code/base_fct.py & sleep 1; ps -aux | grep -i python3; nvidia-smi; sleep 5"
