name: gpu_access_test


services:

  test:
    image: rr5555/gpu_access_test:test_both
    runtime: nvidia
    deploy:
      restart_policy:
        condition: on-failure

    entrypoint: >
      bash -c "printf 'import torch\\nimport time\\na = torch.randn([10, 10]).cuda()\\ntime.sleep(5)\\nprint(\"Done\")' | python3 & sleep 1; nvidia-smi; printf 'import torch\\nprint(torch.cuda.list_gpu_processes())' | python3"
