name: gpu_access_test


services:

  test:
    image: rr5555/gpu_access_test:test_nvidia_smi
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids:
              - "0"
            capabilities: [gpu]


    entrypoint: >
      bash -c "nvidia-smi"
