version: "0.1"
name: gpu_access_test


services:

  test:
    image: rr5555/gpu_access_test:test_pynvml
    runtime: nvidia
    deploy:
      restart_policy:
        condition: on-failure

    entrypoint: >
      bash -c "printf 'import torch\\nprint(f\"torch.cuda.is_available():{torch.cuda.is_available()}\")\\nprint(f\"torch.cuda.device_count():{torch.cuda.device_count()}\")' | python3"
